fix: allow for nullable property access
justinfagnani/jexpr pull request #2
Opened 2021-01-31 12:20 UTC by bennypowers

## What I Did:

- Use `?.` optional chaining to access the results of `this.receiver.evaluate()`

2021-03-05 08:55 UTC, bennypowers commented
## Benchmarks:

### Branch:

```
eval identifier x 873,475,268 ops/sec ±0.55% (93 runs sampled)
native identifier x 851,146,029 ops/sec ±1.57% (86 runs sampled)
eval complex x 6,903,084 ops/sec ±2.19% (86 runs sampled)
native complex x 847,210,764 ops/sec ±1.12% (92 runs sampled)
```

### Master:

```
eval identifier x 870,112,252 ops/sec ±0.51% (94 runs sampled)
native identifier x 867,967,077 ops/sec ±0.76% (92 runs sampled)
eval complex x 7,587,671 ops/sec ±1.51% (88 runs sampled)
native complex x 867,284,566 ops/sec ±0.42% (93 runs sampled)
```

2021-03-13 18:33 UTC, justinfagnani requested changes

2021-03-13 18:33 UTC, justinfagnani commented on src/lib/parser.ts
> +    } else if (right.type === 'Literal' && (right as Literal).value === null) {
I don't think it's possible to enter this case. The right-hand side of a `.` operator should always be an ID or Invoke. The test cases you have don't look like they enter here, they just have IDs of `nullable` and `nulled`.

2021-03-13 18:33 UTC, justinfagnani commented on src/test/parser_test.ts
> +    assert.equal(parser!.parse('data.nullable', astFact)?.evaluate({ data: null }), null);
This test should be in eval_test.ts, and use the `expectEval` helper there.

2021-03-14 08:36 UTC, bennypowers commented on src/test/parser_test.ts
> +    assert.equal(parser!.parse('data.nullable', astFact)?.evaluate({ data: null }), null);
moved over and refactored, thanks

2021-03-14 08:36 UTC, bennypowers commented on src/lib/parser.ts
> +    } else if (right.type === 'Literal' && (right as Literal).value === null) {
confirmed; removed this case.

2021-03-25 16:09 UTC, justinfagnani approved these changes
Thanks!

2021-03-25 16:09 UTC, merged